name: Cat Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.7.0

    - name: Set up Python3
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
      continue-on-error: true
